require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'config.ru'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Naming/PredicateName:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Metrics/BlockLength:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/RenderInline:
  Enabled: false
