language: minimal

services:
  - docker

env:
  - BlACK_CANDY_MEDIA_PATH=./test/fixtures/files

before_script:
  - docker-compose -f docker-compose.test.yml run --rm test_web bash -c "bundle && yarn"

script:
  - docker-compose -f docker-compose.test.yml run --rm test_web bash -c "rails lint:all"
  - docker-compose -f docker-compose.test.yml run --rm test_web bash -c "rails test"
