version: '3.0'
services:
  web:
    build: .
    volumes:
      - .:/app
      - ~/media_data:/root/media_data
      - bundler_data:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
  postgres:
    image: groonga/pgroonga:2.1.8-alpine-11.1
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:4.0-alpine
    volumes:
      - redis_data:/data
volumes:
  bundler_data:
  db_data:
  redis_data:
