version: '3.4'
services:
  app:
    build:
      context: .
      target: dev
    image: blackcandy/base
    volumes:
      - .:/app
      - ~/media_data:/media_data
      - bundler_data:/usr/local/bundle
    entrypoint: docker/dev_entrypoint.sh
    command: ["bin/rails", "s", "-b", "0.0.0.0"]
    ports:
      - 3000:3000
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      REDIS_DATA_URL: redis://redis:6379/0
      REDIS_SIDEKIQ_URL: redis://redis:6379/1
      MEDIA_PATH: /media_data
      WEBPACKER_DEV_SERVER_HOST: webpacker
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    logging:
      driver: none
  redis:
    image: redis:4.0-alpine
    volumes:
      - redis_data:/data
    logging:
      driver: none
  webpacker:
    image: blackcandy/base
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      - bundler_data:/usr/local/bundle
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
    ports:
      - 3035:3035
  worker:
    image: blackcandy/base
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - ~/media_data:/media_data
      - bundler_data:/usr/local/bundle
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      REDIS_SIDEKIQ_URL: redis://redis:6379/1
    depends_on:
      - postgres
      - redis
volumes:
  bundler_data:
  db_data:
  redis_data:
