development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { "redis://localhost:6379/3" } %>
  channel_prefix: black_candy_production
