development:
  adapter: async

test:
  adapter: test

<% if ENV["REDIS_URL"].present? || ENV["REDIS_CABLE_URL"].present? %>
production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL", ENV["REDIS_URL"]) %>
  channel_prefix: black_candy_production
<% else %>
production:
  adapter: async
<% end %>
