development:
  adapter: litecable

test:
  adapter: test

<% if BlackCandy::Config.redis_cable_url.present? %>
production:
  adapter: redis
  url: <%= BlackCandy::Config.redis_cable_url %>
  channel_prefix: black_candy_production
<% else %>
production:
  adapter: litecable
<% end %>
