default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3


<% if BlackCandy::Config.database_adapter == "postgresql" %>
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= BlackCandy::Config.database_url %>
<% else %>
production:
  <<: *default
  database: db/production.sqlite3
<% end %>
