sqlite_default: &sqlite_default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

pg_default: &pg_default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


<% if BlackCandy::Config.db_adapter == "postgresql" %>
development:
  <<: *pg_default
  username: <%= ENV['POSTGRES_USERNAME'] %>
  database: blackcandy_development
  host: localhost

test:
  <<: *pg_default
  username: <%= ENV['POSTGRES_USERNAME'] %>
  database: blackcandy_test
  host: localhost

production:
  <<: *pg_default
  url: <%= BlackCandy::Config.db_url %>
<% else %>
development:
  <<: *sqlite_default
  database: storage/development.sqlite3

test:
  <<: *sqlite_default
  database: storage/test.sqlite3

production:
  <<: *sqlite_default
  database: storage/production.sqlite3
<% end %>
