sqlite_default: &sqlite_default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

pg_default: &pg_default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= BlackCandy::Config.db_url %>

development:
  <<: *sqlite_default
  database: storage/development.sqlite3

<% if BlackCandy::Config.db_adapter == "postgresql" %>
test:
  <<: *pg_default

production:
  <<: *pg_default
<% else %>
test:
  <<: *sqlite_default
  database: storage/test.sqlite3

production:
  <<: *sqlite_default
  database: storage/production.sqlite3
<% end %>
