name: CI

on: [push, pull_request]

jobs:
  test_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install
      - name: Test and Lint
        env:
          RAILS_ENV: test
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev imagemagick ffmpeg
          bundle exec rails db:setup
          bundle exec rails lint:all
          bundle exec rails test:all

      - name: Push coverage data to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
