name: CI

on: [push, pull_request]

jobs:
  test_lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6
        ports: ['6379:6379']
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: 12.20.0
          cache: 'yarn'
      - run: yarn install
      - name: Test and Lint
        env:
          DB_HOST: localhost
          DB_USER: postgres
          REDIS_DATA_URL: redis://localhost:6379/0
          REDIS_SIDEKIQ_URL: redis://localhost:6379/1
          REDIS_CABLE_URL: redis://localhost:6379/2
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev imagemagick ffmpeg
          bundle exec rails db:setup
          bundle exec rails lint:all
          bundle exec rails test:all
          bundle exec brakeman

      - name: Push coverage data to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
